### ISSUE TITLE
nextflow command for running metaphlan3

### ISSUE THREAD

**Issue by lwaldron** [waldronlab/curatedmetagenomics#25]
Make a nextflow command for running MetaPhlAn3 using the docker container. 
    - inputs: corresponds to MetaPhlAn3 flags, including fastq input file, chocophlan and uniref databases
    - outputs: three MetaPhlAn output files (bugs list, marker presence, marker abundance)

**Comment by seandavi** [comment]
I have a working nextflow pipeline running locally. Working on transitioning to run on docker and then on GCP.
