### ISSUE TITLE
Update docker to use metaphlan from March, 2020

### ISSUE THREAD

**Issue by seandavi** [waldronlab/curatedmetagenomics#28]
The February build of metaphlan seems to have a bug that precludes successful download of database. It looks like a rebuild of the docker image using the same dockerfile may do the trick.

**Comment by seandavi** [comment]
Looks like the version should be at least: metaphlan-3.0.0a1

**Comment by fbeghini** [comment]
4550e8e1c1438846659ace0dd2254b6ef69d21c4 I had to force the update of the package, I don't know why, but it was always installing the first build and not the latest one.

**Comment by lwaldron** [comment]
I think this is closed then by 4550e8e? Might have been caching on Dockerhub.
