### ISSUE TITLE
cmd_pipeline should take command-line arguments 

### ISSUE THREAD

**Issue by fbeghini** [waldronlab/curatedmetagenomics#30]
I'm worried that the command line will be too verbose if all the arguments are specified.
To reduce it, I was thinking to organize all the DBs under a folder (DB_PATH), which it contains three directories with fixed name (metaphlan_db, humann/chocophlan, humann/uniref), so we have three less parameters to use

**Comment by fbeghini** [comment]
Also, I'm considering for the usage of a config file, e.g. database URLs and name should be set there. @lwaldron, what do you think?

**Comment by lwaldron** [comment]
I'm not sure - I'd like to understand how it will fit in with a Nextflow workflow like https://github.com/seandavi/curatedMetagenomicsNextflow and be sure it's workflow-friendly.
