### ISSUE TITLE
identify canonical example

### ISSUE THREAD

**Issue by vjcitn** [waldronlab/curatedmetagenomics#4]

**Comment by lwaldron** [comment]
A couple small datasets that exemplify most (all?) of the challenges of building curatedMetagenomicData are [AsnicarF_2017](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/curated/AsnicarF_2017/AsnicarF_2017_metadata.tsv) (example with two body sites) and 
[BritoIL_2016](https://github.com/waldronlab/curatedMetagenomicDataCuration/blob/master/inst/curated/BritoIL_2016/BritoIL_2016_metadata.tsv) (example with multiple SRR accessions per sample). The "NCBI_accession" column provides the input for the [curatedMetagenomicData_pipeline.sh](https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/master/curatedMetagenomicData_pipeline.sh) function, e.g. as shown in [curatedMetagenomicData_pipeline_allsamples.sh](https://github.com/waldronlab/curatedMetagenomicDataHighLoad/blob/master/curatedMetagenomicData_pipeline_allsamples.sh). These will be run in the [Docker container](https://github.com/waldronlab/curatedMetagenomicDataHighLoad/tree/master/docker). Looping in @seandavi.

**Comment by lwaldron** [comment]
Canonical examples now are, 
* a small study: https://storage.googleapis.com/data-curatedmetagenomics/AsnicarF_2017.tar.gz
* a big study: https://storage.googleapis.com/data-curatedmetagenomics/AsnicarF_2021.tar.gz

There are more data in this bucket, just requires any Google sign-in.
